server:
  port: 8080
  
spring:
  application:
    name: user
    
say-hello:
  ribbon:
    eureka:
      enabled: true
    #listOfServers: localhost:8090,localhost:8091,localhost:8092 
    ServerListRefreshInterval: 15000